### ISSUE TITLE
Slower source-to-IL compilation, slower JIT compilation.

### ISSUE THREAD

**Issue by ekalchev** [lsoft/DpdtInject#62]
I saw this mentioned as drawback 

Slower source-to-IL compilation, slower JIT compilation.

Does JIT compilations times outweigh performance penalty of using reflection?

**Comment by lsoft** [comment]
@ekalchev Hello. 

> Does JIT compilations times outweigh performance penalty of using reflection?

No, it does not outweigh , of course. Reflection is completely out of scope because its horrible performance. I mentioned these drawbacks because only for considerations of completeness. (I did not estimate its weight, and suspect it is small)
